### PR TITLE
Improve labelling of timezone dropdown

### PR DESCRIPTION
**Pull request by angussidney**

### CODE REVIEW

**Comment by angussidney** [comment]
This is not needed as long as we fix the automatic timezone selection issue.

**Comment by angussidney** [comment]
Just set up a proper dev environment, surprisingly this works. However, you can only notice the difference in Firefox due to #81. 

image

Although this PR may become redundant, I think it would be worthwhile including it anyway if the user's timezone is not able to be automatically selected for some reason.

**Comment by pl4nty** [comment]
That's a good point on fallback, but from the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/resolvedOptions#browser_compatibility) it looks like the most recent browser without the tz property was released in 2017. Still, it's a super easy fix so may as well

**Comment by pl4nty** [comment]
Added to #81 since I didn't want to fix the merge conflict, sorry!

**Comment by pl4nty** [comment]
I'll add you as a coauthor on #81

**Pull request closed without merging**
