### PR TITLE
feat: rework FAB and add option to hide weekdays

### PR DESCRIPTION
**Pull request by pl4nty**

### CODE REVIEW

**Comment by pl4nty** [comment]
The new FAB component should make #79 pretty trivial too

**Comment by ashleylamont** [comment]
App breaks if you close the week start dialog

Win11 x86 64bit 22000.434 (21H2)
OperaGX LVL3 (core: 82.0.4227.50)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 OPR/82.0.4227.50


https://user-images.githubusercontent.com/59380148/151154995-69045eee-2fc3-44dc-a83d-1ab081bb3b5c.mp4

**Comment by ashleylamont** [comment]
Otherwise lgtm! I'm not super familiar with react so idk too much about the exact implementation, but seems fine apart from the bug.

**Review by ashleylamont — CHANGES_REQUESTED** [review]
(see above messages)

**Comment by pl4nty** [comment]
lmao thanks for spotting that! I noticed another bug in WeekStartAction, where Week 1 changes depending on the week start. Not a regression though, just ported from the existing implementation, so I'm happy to merge and fix it later.

**Comment by pl4nty** [comment]
That was a tricky one. I might have a go at scaling issues next, that or PDF export

**Comment by ashleylamont** [comment]
Looks great, two things, first should it react to you changing the date in the select field? Also, should it hide the options that are hidden from that list?

**Comment by pl4nty** [comment]
Sounds good, I wasn't sure about delaying the rerender (simpler but less reactive) so I'll fix that.

Can't hide options from the list though, otherwise users wouldn't be able to un-hide them.

**Comment by ashleylamont** [comment]
> Can't hide options from the list though, otherwise users wouldn't be able to un-hide them.

I meant in the start of week input 😅 all good though either way

**Comment by pl4nty** [comment]
@ashleylamont oh lol, done

**Comment by ashleylamont** [comment]
https://user-images.githubusercontent.com/59380148/151686232-bd06fd68-7830-47a9-952b-f9962748ce9b.mp4

It doesn't handle changes correctly the first time you open it?

**Comment by pl4nty** [comment]
Should be fixed now, for both week start and hidden days

**Comment by pl4nty** [comment]
there's a regression in 3392b45, it breaks the indexes of weekStart elements (eg Monday = 0 if Sunday is hidden)

**Comment by pl4nty** [comment]
@ashleylamont that should be everything, lmk what you think. the week behaviour on late start days (eg Friday) is interesting, but similar to current and makes sense in a way. once I've merged this, I'll try and finish the course colour picker

**Review by ashleylamont — APPROVED** [review]
LGTM, again not super well versed in react and pretty tired from RLT training and moving so probs best to get @OliverBalfour or someone else to give it a quick once over as well, but otherwise seems good!

**Review by OliverBalfour — APPROVED** [review]
LGTM! Refactor looks good, and I can't find any bugs

**Pull request merged**
