### PR TITLE
feat: move to Sass and cleanup index.scss

### PR DESCRIPTION
**Pull request by ashleylamont**
Add SCSS and cleanup index.scss

### CODE REVIEW

**Review by pl4nty — APPROVED** [review]
LGTM, but I've barely touched styling. Thoughts @OliverBalfour?

**Comment by ashleylamont** [comment]
> LGTM, but I've barely touched styling. Thoughts @OliverBalfour?

Fwiw the styling should all be exactly the same and just get compiled out to a functionally identical .css file by webpack, but fair fair I'll wait to hear what Oliver says 😅

**Comment by pl4nty** [comment]
Ahhh that makes sense, I'm happy if you want to merge then. Wasn't 100% sure what I was looking at rip.

**Comment by OliverBalfour** [comment]
Code LGTM, haven't tested for styling regressions

**Pull request merged**
