### PR TITLE
Fix underscore scraping bug

### PR DESCRIPTION
**Pull request by CraftyDH**
Prevents the scraper from erroring out on GERM2103, where the regex fails due to an underscore in the normal place of a hyphen.

### CODE REVIEW

**Comment by pl4nty** [comment]
Is "Err" for failed matches, or just events without an activity? Would "" be better in the latter case?

**Comment by CraftyDH** [comment]
Yea it is, problem with "" is it will cause this.

Normal: COMP1100 LecA 1
Err: GERM2305 Err 1
Space: GERM2305 1

Meanwhile German still has
LecA, And LecB.

And I think it is better to show an error on things like this than passively ignoring the problem. Though a better indicator could be possible.

**Comment by pl4nty** [comment]
Ah cool, if it's for events with unknown activities that makes sense. I feel like "Err" is probs the best we'll get for a 3-letter explanation, rather than "Unknown" or something

**Review by pl4nty — APPROVED** [review]
LGTM!

**Pull request merged**
