### PR TITLE
Print and export to PNG

### LINKED ISSUE #92: Export timetable screenshot (PNG, JPEG, PDF)
The issue that it's difficult to screenshot your entire schedule on a small screen was raised in #86. Rather than make some events too small, it's better to add a screenshot export button like the old anutimetable.com had that captures the entire calendar, even offscreen bits.

### PR DESCRIPTION
**Pull request by pl4nty**
* Fixes #92

### CODE REVIEW

**Comment by pl4nty** [comment]
@pstefa turns out I used `html-to-image` too lol. I tried to address the comments in your PR, and borrowed the icon. lmk what you think. major difference is this exports the entire day - maybe we can find the earliest and latest times in the view, and add an hour (pretty sure there's a FullCalendar function to get all in-memory events)

**Comment by pl4nty** [comment]
btw the scaling is very janky, I'll try and merge pl4nty/responsive first which should fix that

**Comment by pstefa1707** [comment]
Cool, hopefully that merge will fix some of the issues.

Current bugs:
1. Printing week loses the right most day (due to scaling I assume)
2. Exporting day to PNG doesn't export all hours
3. Exporting agenda to either PNG or PDF will cause errors in terminal

I think we restrict exporting to just the week view to cut down scope and work from there?

**Comment by pl4nty** [comment]
The PNG looks perfect! But the printing seems to cut off days horizontally (especially when it defaults to portrait), and some later classes can spill onto a second page

**Pull request merged**
