### PR TITLE
feat: run CI on PRs from forks

### LINKED ISSUE #34: Approval workflow for CI on PRs from forks
Currently PRs from forks run in the fork context (pull_request) and don't have access to deploy creds, so fail. Seems like a regression related to pull_request_target, but we need a secure workflow to approve CI for a build and avoid credential theft risks (contributors to approve?).

### PR DESCRIPTION
**Pull request by pl4nty**
* Fixes #34

### CODE REVIEW

**Review by ashleylamont — COMMENTED** [review]
It all LGTM and the move from pull_req to pull_req_target seems sensible going by documentation but I'm not *too* well versed in CI and Azure so possibly best for @OliverBalfour to have a look as well

**Comment by OliverBalfour** [comment]
My experience doing CI stuff has always been to just merge into master to test it. The changes look good and there's only one way to find out if they work

Is it possible to test this first by making a PR into this feature branch? If so I'd like to do this before merge but testing after merging also isn't too bad as this isn't student facing

**Comment by pl4nty** [comment]
Good idea, I remember deciding to run CI on non-master PRs, but didn't think about using it to test the target branch's workflow. Testing in #94

**Comment by pl4nty** [comment]
The tests passed, but I'd like to wait until tonight for merging in case anything breaks. Also need to give the workflows a display name

**Pull request merged**
